---
- name: Verify
  hosts: all
  gather_facts: true
  vars:
    kubectx_for_all_users: true
    command_shell: bash
  tasks:
    - name: Set download directory if install only for the user
      ansible.builtin.set_fact:
        kubectx_runtime_dir: "{{ ansible_user_dir }}/bin"
      when: not kubectx_for_all_users | bool

    - name: Set download directory for all users to use
      ansible.builtin.set_fact:
        kubectx_runtime_dir: "/usr/local/bin"
      when: kubectx_for_all_users | bool

    - name: Find the kubectx file
      ansible.builtin.stat:
        path: "{{ kubectx_runtime_dir }}/kubectx"
      register: kubectx_file

    - name: Print stat info
      ansible.builtin.debug:
        msg: "{{ kubectx_file.stat }}"

    - name: Assert that kubectx exists
      ansible.builtin.assert:
        that: kubectx_file.stat.exists

    - name: Assert that kubectx is executable
      ansible.builtin.assert:
        that: kubectx_file.stat.executable
