---
- name: Verify
  hosts: all
  gather_facts: true
  vars:
    kubectx_for_all_users: true
    command_shell: bash
  tasks:
    - name: Set download directory if install only for the user
      ansible.builtin.set_fact:
        kubectx_runtime_dir: "{{ ansible_user_dir }}/bin"
      when: not kubectx_for_all_users | bool

    - name: Set download directory for all users to use
      ansible.builtin.set_fact:
        kubectx_runtime_dir: "/usr/local/bin"
      when: kubectx_for_all_users | bool

    - name: Loop through binaries
      ansible.builtin.set_fact:
        binaries: ["kubectx", "kubens"]

    - name: Find the binary files
      ansible.builtin.stat:
        path: "{{ kubectx_runtime_dir }}/{{ item }}"
      register: binary_files
      loop: "{{ binaries }}"

    - name: Print stat info
      ansible.builtin.debug:
        msg: "{{ item.item }}: {{ item.stat }}"
      loop: "{{ binary_files.results }}"

    - name: Assert that binaries exist
      ansible.builtin.assert:
        that: item.stat.exists
      loop: "{{ binary_files.results }}"

    - name: Assert that binaries are executable
      ansible.builtin.assert:
        that: item.stat.executable
      loop: "{{ binary_files.results }}"
